inherit_from:
  - .rubocop_airbnb.yml

# Rails用に最適化
Rails:
  Enabled: true

# 文字数上限
LineLength:
  Max: 130

# スキャン適用外のフォルダ、ファイル
AllCops:
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - "lib/tasks/auto_annotate_models.rake"
    - "node_modules/**/*"
    - "bin/*"
    - "**/Gemfile"
    - "vendor/**/*"
    - ".git/**/*"
